baseURL = 'https://devicode.io'
languageCode = 'en-us'
title = 'DeviCode'
theme = 'puppet'
googleAnalytics = "G-65SCCZ7Y92"

[Params.giscus]
	enable = "true"
	repo = "JeffersonAmori/DeviCode"
	repo_id = "R_kgDOIz_rQw"
	category = "Announcements"
	category_id = "DIC_kwDOIz_rQ84CTtV0"
	mapping = "og:title"
	strict = "0"
	reactions_enabled = "1"
	emit_metadata = "0"
	input_position = "top"
	theme = "light"
	lang = "pt"
	loading = "lazy"
	crossorigin = "anonymous"